### ISSUE TITLE
"npm run release" updates release.zip if it already exists

### ISSUE THREAD

**Issue by kasperwelbers** [eyra/feldspar#14]
When you make a new release with "npm run release", and release.zip already exists, it updates the zip folder instead of overwriting it. 

As a result, you can end up with multiple versions of your build inside release.zip, and you might not see any updates when uploading the new version to Next. I also had some weird errors with loading web workers, that was (somehow) resolved after removing the old versions.

Specifically, the problem is in package.json, inside:
`"archive": "cd build && zip -r ../release.zip .",`

release.zip should be overwritten, not updated.

**Comment by emielvdveen** [comment]
Thanx for reporting this issue. I will fix this and think of a solution with some sort of build nr
