### ISSUE TITLE
Print state on screen during extraction

### ISSUE THREAD

**Issue by emielvdveen** [eyra/feldspar#18]

**Comment by emielvdveen** [comment]
<img width="2002" alt="Screenshot 2024-06-27 at 16 28 24" src="https://github.com/eyra/feldspar/assets/262448/b6334a25-3b52-4eaa-adeb-fc6e0fe05f14">

**Comment by emielvdveen** [comment]
@TjerkNan You can test this feature using the Feldspar release below:

[feldspar_2024-06-27_71.zip](https://github.com/user-attachments/files/16027730/feldspar_2024-06-27_71.zip)

**Comment by TjerkNan** [comment]
It works but it is slow, maybe done on purpose for testing (as loading a file like this is always very fast?) If that's the case, this issue can be closed.

https://github.com/eyra/feldspar/assets/88683839/aeac5e3b-0c87-4d18-ace8-4f5b0f81a361

**Comment by emielvdveen** [comment]
@TjerkNan the slowness is on purpose indeed for demo reasons. See line 130 in https://github.com/eyra/feldspar/blob/master/src/framework/processing/py/port/script.py 

You can clone the Feldspar repo, change line 130 en execute `npm run release`. You can then find the newly created release zip file in the releases folder.

**Comment by TjerkNan** [comment]
Heb je instructies opgevolgd en gelukt
