### ISSUE TITLE
The data selection made by the participant is not honoured

### ISSUE THREAD

**Issue by TjerkNan** [eyra/feldspar#22]
**Describe the bug**
When a participant selects which data to donate via the 'adjust' option, all data seems to be donated anyway. 

**To Reproduce**
1. As a researcher use attached feldspar app in workflow
2. As a participant visit published url and donate data with no selection
3. as a different participant visit published url and donate with selection
4. As a researcher export all data
5. Observe that the json files in the exported data are identical. 

**Expected behavior**
A difference in the contents of the json, that reflects the selection made by the participant.

**Supporting files to recreate the test**

[demo.zip](https://github.com/user-attachments/files/16909041/demo.zip)

[example_export.zip](https://github.com/user-attachments/files/16909080/example_export.zip)

**Comment by mellelieuwes** [comment]
@TjerkNan can not reproduce this issue with the latest Feldspar example flow:

- Feldspar example flow: [feldspar_2024-09-20_12.zip](https://github.com/user-attachments/files/17077302/feldspar_2024-09-20_12.zip)
- Data packet: [demo.zip](https://github.com/user-attachments/files/17077298/demo.zip)
- Exported data: [20240920_new_project_7.zip](https://github.com/user-attachments/files/17077294/20240920_new_project_7.zip)

Can you re-test it with this feldspar example flow?

**Comment by TjerkNan** [comment]
@mellelieuwes I have downloaded the linked test files but the issue persists for me in Firefox on mac.
